logging:
  output: stdout
  level: info

alerts:
  on_failure:
    # Execute a command when a task fails
    - type: cmd
      cmd: |
        cat <<- EOF >> .tmp/failed.txt 
        {{ start_time }}: {{ task_name }} failed with exit code {{ exit_code }}
        stdout: {{ stdout }}
        stderr: {{ stderr }}
        {{ debug_info }}
        ---
        EOF
  on_success:
    # Execute a command when a task success
    - type: cmd
      cmd: |
        cat <<- EOF >> .tmp/succeed.txt
        task_name: '{{ task_name }}'
        exit_code: '{{ exit_code }}'
        start_time: '{{ start_time }}'
        duration: '{{ duration }}'
        end_time: '{{ end_time }}'
        error_message: '{{ error_message }}'
        debug_info: '{{ debug_info }}'
        stdout: '{{ stdout }}'
        stderr: '{{ stderr }}'
        ---
        EOF

tasks:
  - name: debug1
    cmd: 'date -Ins >> .tmp/times1.txt'
#    every: 5s
    when: '* *-*-* *:*:*/10'
    time_limit: 2s
    shell: '/usr/bin/fish'

  - name: DEBUG2
    cmd: 'date -Ins >> .tmp/times2.txt'
    every: 2s
#    when: '* *-*-* *:*:*/2'
    time_limit: 2s
    shell: '/usr/bin/fish'

#  - name: Task1
#    cmd: echo 'hello'
#    when:
#      day_of_week:
#        - Mon
#        - tHu
#      year: '*'
#      month: '*'
#      day: '*/2'
#      hour: 12
#      minute: 0
#      second: 0
#
#  - name: Task2
#    cmd: echo 'hello'
#    when: '[Mon,Tue] *-*/2-01 12:00:00'
#
#  - name: Task3
#    cmd: echo 'hello'
#    when: '[Mon,Thu] 14..18-*/5+2-[2, 15, 24] 12:00:00'
#
#  - name: Task4
#    cmd: date
#    when: '* *-*-* *:*:*/5'
#    avoid_overlapping: true
#    run_as: root:root
#
#  - name: Task5
#    cmd: echo 'hello'
#    when: '[Mon,Thu] 14..18-*/5+2-00 12:00:*'
#    timezone: 'Europe/Madrid'
